name: Test

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Test CommonJS
        uses: ./
        with:
          working-directory: fixtures/commonjs
          block-esm: false

      - name: Test ESModule
        uses: ./
        with:
          working-directory: fixtures/esmodule
          block-esm: false

      - name: Test CommonJS
        uses: ./
        with:
          working-directory: fixtures/commonjs
          block-esm: true

      - name: Test ESModule
        uses: ./
        with:
          working-directory: fixtures/esmodule
          block-esm: true
