name: Test

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Test
        uses: ./
        with:
          working-directory: test-assets
